/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;


import controles.CadastroControles;
import entidades.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaConsulta extends javax.swing.JFrame {

    private ArrayList<Produto> listaProdutos;
    private DefaultTableModel tableModel;
    CadastroControles controlador; 
    ArrayList<Produto> listaProdutosExibida;

    public TelaConsulta(ArrayList<Produto> listaProdutos) {
        initComponents();
        this.listaProdutos = listaProdutos;
        initializeTableModel();
        updateTableData();
    }
   public TelaConsulta(ArrayList<Produto> listaProdutosExibida, CadastroControles controlador) {
        initComponents();
        controlador = new CadastroControles();
        listaProdutosExibida = new ArrayList<>();
        carregarProdutosNaLista(); // Adiciona esta chamada para carregar os produtos na lista
    }


    public void carregarProdutosNaLista() {
        // Lógica para carregar os produtos na listaProdutosExibida
        listaProdutosExibida = controlador.obterListaProdutos();
    // Este método chama para atualizar a tabela com os dados da listaProdutosExibida
    }
private void updateTableData(Iterable<Produto> listaProdutosExibida) {
    DefaultTableModel model = (DefaultTableModel) jTableProdutos.getModel();
    model.setRowCount(0); // Limpa todas as linhas existentes na tabela
    for (Produto produto : listaProdutosExibida) {
        // Adiciona uma nova linha na tabela para cada produto
        model.addRow(new Object[]{produto.getCodigo(), produto.getNome(), produto.getPrecoVenda()});
    }
}

    private void initializeTableModel() {
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Código");
        tableModel.addColumn("Nome");
        tableModel.addColumn("Preço Venda");
        tableModel.addColumn("Preço Custo");
        tableModel.addColumn("Habilitado Vendas");
        jTableProdutos.setModel(tableModel);
    }

    private void updateTableData() {
        tableModel.setRowCount(0); // Limpar a tabela antes de atualizar
        for (Produto produto : listaProdutos) {
            Object[] rowData = {
                produto.getCodigo(),
                produto.getNome(),
                produto.getPrecoVenda(),
                produto.getPrecoCusto(),
                produto.isHabilitadoVendas()
            };
            tableModel.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

 private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {
    int selectedRow = jTableProdutos.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um produto para excluir.");
        return;
    }

    int confirmacao = JOptionPane.showConfirmDialog(this, "Deseja excluir este produto?", "Confirmação", JOptionPane.YES_NO_OPTION);

    if (confirmacao == JOptionPane.YES_OPTION) {
        long codigoProduto = (long) jTableProdutos.getValueAt(selectedRow, 0);
        CadastroControles controlador = new CadastroControles();

        if (controlador.excluirProduto(codigoProduto)) {
            JOptionPane.showMessageDialog(this, "Produto excluído com sucesso.");
            carregarProdutosNaLista(); // Atualiza a lista após a exclusão
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir o produto.");
        }
    }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdutos;
    // End of variables declaration//GEN-END:variables
}
